### ISSUE TITLE
TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by jorgutdev** [DimitriMikadze/firebase-react-native-redux-starter#10]
Hello, 

thanks for the boilerplate @DimitriMikadze  
I've install it with `npm install` but when running this error appears 
![image](https://user-images.githubusercontent.com/30719489/29540961-8fc59d76-86d1-11e7-8994-5dac05c7fe92.png)

This is the output from `npm run test`
```
jorge@linux:~/firebase-react-native-redux-starter$ npm run test

> rnauth@0.0.1 test /home/jorge/firebase-react-native-redux-starter
> jest


 RUNS  __tests__/index.android.js
 RUNS  __tests__/index.ios.js
 FAIL  __tests__/index.android.js
  ● Test suite failed to run

    TypeError: Cannot read property 'style' of undefined
      
      at Object.<anonymous> (node_modules/react-native-router-flux/src/Scene.js:30:105)
      at Object.<anonymous> (node_modules/react-native-router-flux/src/Actions.js:10:12)
      at Object.<anonymous> (node_modules/react-native-router-flux/index.js:1:398)

 FAIL  __tests__/index.ios.js
  ● Test suite failed to run

    TypeError: Cannot read property 'style' of undefined
      
      at Object.<anonymous> (node_modules/react-native-router-flux/src/Scene.js:30:105)
      at Object.<anonymous> (node_modules/react-native-router-flux/src/Actions.js:10:12)
      at Object.<anonymous> (node_modules/react-native-router-flux/index.js:1:398)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        6.162s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rnauth@0.0.1 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rnauth@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jorge/.npm/_logs/2017-08-21T22_27_58_935Z-debug.log

```

**Comment by DimiMikadze** [comment]
Hi @jorgutdev, unfortunately can't reproduce same error on my local machine, did you managed to resolve this issue?

**Comment by jorgutdev** [comment]
Hello Dimitri,

I was looking for an easy project to check how call firebase module but about 5 minutes ago finally got working my ignite-redux-sagas example.

About the issue, I just followed the guide from the readme.md but couldn't get it working.

Sorry and I appreciate your time.

**Comment by DimiMikadze** [comment]
Hi @jorgutdev sorry too hear that, thank you for your feedback!
